apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: task-manager
data:
  MONGODB_URI: mongodb://mongodb:27017/mydatabase
  NODE_ENV: development
  FRONTEND_BASE_URL: "http://taskmanager.local"
  PORT: "5000"
  COOKIE_SECRET: someSecretValue

